Na řešení se musí všichni podíllet, ale mohou odevzdat všichni.

Každé řešení musí vyjmenovat všechny členy týmu, podle vzoru (ID recodexu, bude tam nějakej hash).

In [36]:
import numpy as np

In [2]:
np.__version__

'2.1.1'

In [3]:
[1,2,3]

[1, 2, 3]

In [6]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Zjistí mi rozměry matice
a.shape

(3,)

In [12]:
b.shape

(3, 3)

In [15]:
a + 2

array([3, 4, 5])

In [16]:
# Jako maticové násobení se může použít zavináč
a @ b

array([6., 6., 6.])

In [17]:
# Hodí se když mám sloupcový vektor a chci z toho udělat řádkový vektor
np.expand_dims(a,1)

array([[1],
       [2],
       [3]])

In [26]:
# no.concatenate([a,b])
# spojuje matice: axis=0 - pod sebe
#                axis = 1 - vedle sebe
# np.stack([a,b]) poté přidává další rozměr
# může být užitečný, když má člověk v každém řádku trénovací příklad a chce z toho udělat nějaké batche, může mít poté rozdělený celý dataset na kusy dat, které se postupně paralelně zúracovávají
# np.sum(a) - sečte všechny prvky
# np.mean(a) - průměr
# np.std(a) - standardní odchylka
print(a)
print(a[0])
print(a[-1])

[1 2 3]
1
3


In [27]:
import sklearn.datasets

In [28]:
dataset = sklearn.datasets.load_diabetes()  

In [29]:
dataset.data.shape

(442, 10)

In [32]:
dataset.target.shape

(442,)

In [35]:
# Popis datasetu
print(dataset.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee